{
  description = "go-app — generated by flkr";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flkr-templates.url = "github:narvanalabs/flkr-templates";
  };

  outputs = { self, nixpkgs, flkr-templates, ... }:
    flkr-templates.lib.mkApp {
      inherit nixpkgs;
      src = ./.;
      ecosystem = "go";
      version = "1.25.0";
      packageManager = "gomod";
      buildCommand = "go build -o flkr .";
      startCommand = "./flkr";
      port = 8080;
      vendorHash = "sha256-INXKKsT91oKPF7KYGTMKE2kCekumG8zuTylX2yEkIHQ=";
    };
}
